// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqM3P_ffET2rI6VtKWXIFQD0_JP_sHgJ4',
    appId: '1:601654467450:web:ffe8f734ee184bceba54c3',
    messagingSenderId: '601654467450',
    projectId: 'hotel-order-management',
    authDomain: 'hotel-order-management.firebaseapp.com',
    storageBucket: 'hotel-order-management.firebasestorage.app',
    measurementId: 'G-QVMQ7EYYF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_1VBEFgEqLtSpy8uO9rgbwa6C7_8V9L0',
    appId: '1:601654467450:android:074ce8c46c9bd51cba54c3',
    messagingSenderId: '601654467450',
    projectId: 'hotel-order-management',
    storageBucket: 'hotel-order-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdYBRApFs2V6rmNNL3j50EJDuQStme9ho',
    appId: '1:601654467450:ios:992067fb1254e143ba54c3',
    messagingSenderId: '601654467450',
    projectId: 'hotel-order-management',
    storageBucket: 'hotel-order-management.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdYBRApFs2V6rmNNL3j50EJDuQStme9ho',
    appId: '1:601654467450:ios:992067fb1254e143ba54c3',
    messagingSenderId: '601654467450',
    projectId: 'hotel-order-management',
    storageBucket: 'hotel-order-management.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqM3P_ffET2rI6VtKWXIFQD0_JP_sHgJ4',
    appId: '1:601654467450:web:16354c0727cac007ba54c3',
    messagingSenderId: '601654467450',
    projectId: 'hotel-order-management',
    authDomain: 'hotel-order-management.firebaseapp.com',
    storageBucket: 'hotel-order-management.firebasestorage.app',
    measurementId: 'G-3QFSFYXQS7',
  );
}
